name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      zerotierVersion:
        description: Zerotier version to be build
        required: true
        default: '1.6.5'

env:
  APP_NAME: zerotier
  DOCKERHUB_REPO: isayme/zerotier

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Zerotier Version
        run: |
          echo ZEROTIER_VERSION=${{ github.event.inputs.zerotierVersion }} >> $GITHUB_ENV
          echo BUILD_TIME=`date -u +"%FT%TZ"` >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64/v8
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            ZEROTIER_VERSION=${{ env.ZEROTIER_VERSION }}
            BUILD_TIME=${{ env.BUILD_TIME }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.ZEROTIER_VERSION }}
            ${{ env.DOCKERHUB_REPO }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
